# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Use base box with dependenies installed
  config.vm.box = "jcbbjjttt/newhavenio"

  # Forward for access from host browser
  config.vm.network "forwarded_port", guest: 4000, host: 4000

  # Sync repository for editing on host
  config.vm.synced_folder "../", "/home/vagrant/newhavenio.github.io"

end
